### ISSUE TITLE
USB host not working

### ISSUE THREAD

**Issue by hgalindo** [YuzukiHD/OpenWrt#3]
How to enable USB as host under OpenWrt 23.05, is this configuration in dts file correct?:

&usbc0 {
device_type = "usbc0";
usb_port_type = <0x1>;
usb_detect_type = <0x1>;
usb_detect_mode = <0x0>;
usb_id_gpio;
usb_det_vbus_gpio;
/* det_vbus_supply = <&usb_power_supply>; */
usb_regulator_io = "nocare";
usb_wakeup_suspend = <0>;
usb_serial_unique = <0>;
usb_serial_number = "20080411";
status = "okay";
};

it is not detecting any device connected to the USB, what should be the right configuration? thanks.

**Comment by YuzukiTsuru** [comment]
default is usb device, need to set to usb host mode, cat the usb_host node in /sys/
